name: Testing run
run-name: ${{github.actor}} is running UnitTests
on: [push]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.1
      - name: Build
        run: msbuild  -t:restore -p:RestorePackagesConfig=true
      - name: Find
        run: dir * "\StockPredictionTests.dll" /s
      - name: Run tests
        run: dotnet test --no-build 
